#!/usr/bin/env python3
"""
Parsers Documentation Updater

This script scans all Python files in src/parsers/ and updates
the comprehensive API documentation at docs/PARSERS_API.md.

Usage:
    python scripts/update_parsers_docs.py

Or use the GitHub Copilot agent:
    @parsers-doc-agent update the parsers documentation
"""

import os
import ast
import inspect
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Tuple, Optional
import re


class DocstringExtractor(ast.NodeVisitor):
    """Extract classes, functions, and docstrings from Python AST."""
    
    def __init__(self, source: str):
        self.source = source
        self.classes = []
        self.functions = []
        self.module_docstring = None
        
    def visit_Module(self, node):
        """Extract module docstring."""
        self.module_docstring = ast.get_docstring(node)
        self.generic_visit(node)
        
    def visit_ClassDef(self, node):
        """Extract class information."""
        class_info = {
            'name': node.name,
            'docstring': ast.get_docstring(node),
            'lineno': node.lineno,
            'methods': []
        }
        
        # Extract methods
        for item in node.body:
            if isinstance(item, ast.FunctionDef):
                method_info = self._extract_function_info(item)
                if not method_info['name'].startswith('_') or method_info['name'].startswith('__'):
                    class_info['methods'].append(method_info)
        
        self.classes.append(class_info)
        
    def visit_FunctionDef(self, node):
        """Extract standalone functions (not methods)."""
        # Only collect if this is a module-level function
        if isinstance(node, ast.FunctionDef):
            parent = getattr(node, 'parent', None)
            if parent is None or isinstance(parent, ast.Module):
                func_info = self._extract_function_info(node)
                if not func_info['name'].startswith('_'):
                    self.functions.append(func_info)
    
    def _extract_function_info(self, node) -> Dict:
        """Extract function/method information."""
        # Get signature
        args = []
        for arg in node.args.args:
            arg_str = arg.arg
            if arg.annotation:
                arg_str += f": {ast.unparse(arg.annotation)}"
            args.append(arg_str)
        
        # Get return annotation
        returns = ""
        if node.returns:
            returns = f" -> {ast.unparse(node.returns)}"
        
        signature = f"{node.name}({', '.join(args)}){returns}"
        
        return {
            'name': node.name,
            'signature': signature,
            'docstring': ast.get_docstring(node),
            'lineno': node.lineno
        }


def scan_python_file(filepath: Path) -> Dict:
    """Scan a Python file and extract documentation info."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            source = f.read()
        
        tree = ast.parse(source)
        extractor = DocstringExtractor(source)
        extractor.visit(tree)
        
        return {
            'path': filepath,
            'module_docstring': extractor.module_docstring,
            'classes': extractor.classes,
            'functions': extractor.functions
        }
    except Exception as e:
        print(f"Error parsing {filepath}: {e}")
        return None


def scan_parsers_directory(base_path: Path) -> Dict[str, List[Dict]]:
    """Scan all Python files in parsers directory."""
    parsers_path = base_path / "src" / "parsers"
    
    modules = {
        'root': [],
        'diann': [],
        'search': [],
        'timsmeth': [],
        'vneometh': []
    }
    
    # Scan root level
    for py_file in parsers_path.glob("*.py"):
        if py_file.name != "__init__.py":
            info = scan_python_file(py_file)
            if info:
                modules['root'].append(info)
    
    # Scan subdirectories
    for subdir in ['diann', 'search', 'timsmeth', 'vneometh']:
        subdir_path = parsers_path / subdir
        if subdir_path.exists():
            for py_file in subdir_path.glob("*.py"):
                if py_file.name != "__init__.py":
                    info = scan_python_file(py_file)
                    if info:
                        modules[subdir].append(info)
    
    return modules


def generate_markdown_docs(modules: Dict[str, List[Dict]]) -> str:
    """Generate markdown documentation from extracted info."""
    
    timestamp = datetime.now().strftime("%Y-%m-%d")
    
    doc = f"""# Parsers Module API Documentation

**Last Updated:** {timestamp}  
**Auto-generated by:** parsers-doc-agent / update_parsers_docs.py

---

## Table of Contents

- [Overview](#overview)
- [Root Level](#root-level)
"""
    
    # Build TOC for subdirectories
    if modules['diann']:
        doc += "- [diann/ - DIA-NN Search Results](#diann---dia-nn-search-results)\n"
    if modules['search']:
        doc += "- [search/ - Multi-Engine Search Results](#search---multi-engine-search-results)\n"
    if modules['timsmeth']:
        doc += "- [timsmeth/ - Bruker TimsTOF Methods](#timsmeth---bruker-timstof-methods)\n"
    if modules['vneometh']:
        doc += "- [vneometh/ - VanquishNeo LC Methods](#vneometh---vanquishneo-lc-methods)\n"
    
    doc += "\n---\n\n## Overview\n\n"
    doc += "The `parsers` module provides comprehensive tools for parsing, analyzing, and comparing "
    doc += "mass spectrometry method files and search results from various instruments and software platforms.\n\n"
    
    # Document each module
    total_classes = 0
    total_methods = 0
    total_functions = 0
    
    for module_name, files in modules.items():
        if not files:
            continue
            
        if module_name == 'root':
            doc += "## Root Level\n\n"
        else:
            doc += f"## {module_name}/\n\n"
        
        for file_info in files:
            filename = file_info['path'].name
            doc += f"### {filename}\n\n"
            
            if file_info['module_docstring']:
                doc += f"**Purpose:** {file_info['module_docstring'].split(chr(10))[0]}\n\n"
            
            # Document classes
            for cls in file_info['classes']:
                total_classes += 1
                doc += f"#### Class: `{cls['name']}`\n\n"
                
                if cls['docstring']:
                    # Get first few lines
                    doclines = cls['docstring'].split('\n')[:3]
                    doc += ' '.join(doclines) + "\n\n"
                
                doc += "**Methods:**\n\n"
                
                # Document methods
                for method in cls['methods']:
                    total_methods += 1
                    doc += f"##### `{method['signature']}`\n\n"
                    
                    if method['docstring']:
                        doclines = method['docstring'].split('\n')[:5]
                        for line in doclines:
                            if line.strip():
                                doc += line.strip() + "\n"
                    doc += "\n"
            
            # Document standalone functions
            for func in file_info['functions']:
                total_functions += 1
                doc += f"#### Function: `{func['signature']}`\n\n"
                
                if func['docstring']:
                    doclines = func['docstring'].split('\n')[:3]
                    for line in doclines:
                        if line.strip():
                            doc += line.strip() + "\n"
                doc += "\n"
    
    # Summary statistics
    doc += "\n---\n\n## Summary Statistics\n\n"
    doc += f"- **Total classes:** {total_classes}\n"
    doc += f"- **Total methods:** {total_methods}\n"
    doc += f"- **Total functions:** {total_functions}\n"
    doc += f"- **Last scan:** {timestamp}\n\n"
    
    return doc


def main():
    """Main function to update documentation."""
    base_path = Path(__file__).parent.parent
    
    print("Scanning parsers directory...")
    modules = scan_parsers_directory(base_path)
    
    total_files = sum(len(files) for files in modules.values())
    print(f"Found {total_files} Python files to document")
    
    print("Generating documentation...")
    markdown_doc = generate_markdown_docs(modules)
    
    output_path = base_path / "docs" / "PARSERS_API.md"
    output_path.parent.mkdir(exist_ok=True)
    
    print(f"Writing to {output_path}...")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(markdown_doc)
    
    print("✓ Documentation updated successfully!")
    print(f"\nGenerated documentation at: {output_path}")


if __name__ == "__main__":
    main()
