<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ThermoFisher.CommonCore.Data">
      <HintPath>../ThermoFisher.CommonCore.Data.dll</HintPath>
    </Reference>
    <Reference Include="ThermoFisher.CommonCore.RawFileReader">
      <HintPath>../ThermoFisher.CommonCore.RawFileReader.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
